class Secrets {
  static String supabaseUrl="https://tyjkydwnyuokukdjeuel.supabase.co";
  static String supabaseKey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5amt5ZHdueXVva3VrZGpldWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5MDc3NjIsImV4cCI6MjA0NzQ4Mzc2Mn0.uEXFewr587J99awy6EWgGLqKBmDphLxSlvDGNKgHfGw";
}